### ISSUE TITLE
RBM image in detailed record

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#174] opened 2020-01-10 16:29 UTC
@flapka As it is now, large RBM images open up in BlackLight filling up the dedicated image rectangle to the fullest on the small side, in effect presenting a detail of the overall image. This is not the behavior for art collection images, for which users have to zoom in for them to fill the image space.
Would it be okay with your department for RBM images to imitate the art collection and have them open in BlackLight constrained by the default max size of the image rectangle? A smaller version of RBM images appear when you click on them, and that's the image size that should be the default size maybe?

Also, given that they are not IIIF I am copying @yulgit1 to know if there is any technical issues with this proposal.

![Blacklight image for YCBA art item](https://user-images.githubusercontent.com/4093644/72168013-4a22db80-339a-11ea-9a3d-2396a28bc1b4.png)

**Comment by flapka** [comment] 2020-01-10 16:52
@edgartdata @yulgit1 @mxgold  This is a good question; thanks for posing it.

If I've understood it correctly, this variant outcome for RB is the result of two factors that should both be fixed:
1. RB images for objects evaluated as public domain don't yet show up in the same IIIf viewer as art collections. This change should be implemented later this spring? When they do appear in the IIIf viewer, the sizing will automatically be the same as with art collections, right?
2. Some RB images for objects that are not in the public domain are (erroneously) showing up at full size, instead of thumbnail size. As Melissa noted in this morning's meeting, this is caused by inaccurate CDS level assignments in NetX. This will require a methodical round of data fixing, but I've made Laura aware of the issue. Once fixed, these images will show up at thumbnail size.

Solving the two issues above would in effect solve the problem that @edgartdata describes, is that correct? 

I wouldn't mind a fix that renders the full-size images differently (outside of the IIIf viewer), but I defer to others on whether this is a priority.

**Comment by yulgit1** [comment] 2020-01-10 22:30
interface issues resolved in: 
https://github.com/ycba-cia/blacklight-collections2/commit/0056fdb05417eeeec19d9e513ac50ed0acd2e360
https://github.com/ycba-cia/blacklight-collections2/commit/0c15460082b10171db4964ec1f0583315908d8b8

**Closed** 2020-01-24 15:01 UTC
